### ISSUE TITLE
`assert_contains` changed in a semantically-observable manner between 9.5 and 9.6

### ISSUE THREAD

**Issue by shepmaster** [SixArm/assertables-rust-crate#11]
```rust
fn main() {
    let s = String::new();
    assertables::assert_contains!(s, "");
    assertables::assert_contains!(s, "");
}
```

```
% cargo update -p assertables --precise 9.5.0
    Updating crates.io index

% cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/repro`
```

```
% cargo update -p assertables --precise 9.6.0
    Updating crates.io index
    Updating assertables v9.5.0 -> v9.6.0

% cargo run
   Compiling repro v0.1.0 (/private/tmp/repro)
error[E0382]: use of moved value: `s`
 --> src/main.rs:4:35
  |
2 |     let s = String::new();
  |         - move occurs because `s` has type `String`, which does not implement the `Copy` trait
3 |     assertables::assert_contains!(s, "");
  |                                   - value moved here
4 |     assertables::assert_contains!(s, "");
  |                                   ^ value used here after move
  |
help: consider cloning the value if the performance cost is acceptable
  |
3 |     assertables::assert_contains!(s.clone(), "");
  |                                    ++++++++

For more information about this error, try `rustc --explain E0382`.
error: could not compile `repro` (bin "repro") due to 1 previous error
```

**Comment by joelparkerhenderson** [comment]
Thank you. Yes you're exactly right, cargo semver-checks doesn't seem to catch this. What I'm seeing other macro-based projects do is have a large test suite of semantic observations for testing regressions.

> Yes, but I'm not sure I understand the suggestion — the code continues to fail with that version.

Are you able to edit your own source code? 

I.e. in your own source code change code that uses pass-by-value (i.e. read-write ownership) like this…

```rust
assert_contains!(s, "");
```

…into code that uses pass-by-reference (i.e. read-only) like this:

```rust
assert_contains!(&s, "");
```

If you can't easily change your own source code, then a different solution is to pin the exact version that works for you, meaning 9.5.0.

When I suggest to upgrade to 9.6.1, it's not because it fixes your specific pass-by-value question; it's because I found and fixed all the similar issues that turned up related to using pass-by-reference versus pass-by-value, and also added many more tests to catch these issues, and also added new documentation that shows the syntax fixes such as the ampersand.

Thanks again for you help and report-- this is the first hiccup in the project overall so I'm hoping to have more Rust people helping with advice and code.

**Comment by shepmaster** [comment]
> Are you able to edit your own source code?

Yes, but that goes against the point of semver — I should not need to change my source code when upgrading from one semantic version to another.

> pin the exact version that works for you

Yes, that's more-or-less what I've done, but that's only a temporary bandaid while this issue is worked on.

---

However, you may not need to make this an incompatible change. For example, this Rust macro evaluates the argument once and doesn't require ownership:

```rust
use std::cell::Cell;

fn main() {
    // One evaluation
    let counter = Cell::new(0_u8);
    let get_value_and_increment = || {
        counter.set(counter.get() + 1);
        "container"
    };

    println!("{}", get_value_and_increment());

    assert_eq!(1, counter.get());

    // Ownership not required
    let s = String::from("container");
    println!("{}", s);
    assert!(!s.is_empty());
}
```

If we focus on how `println` is implemented (on Rust 1.56 because this has changed more recently):

```rust
println!("{}", String::new());
```

Expands to (cleaned a bit)

```rust
::std::io::_print(
    match match (&String::new(),) {
        (arg0,) => [::core::fmt::ArgumentV1::new(
            arg0,
            ::core::fmt::Display::fmt,
        )],
    } {
        ref args => unsafe { ::core::fmt::Arguments::new_v1(&["", "\n"], args) },
    },
)
```

You could use similar constructs in your macros:

```rust
use std::cell::Cell;

macro_rules! once_by_reference {
    ($v:expr) => {
        match $v {
            ref x => {
                assert!(x.contains("a"));
                assert!(x.contains("e"));
                assert!(x.contains("i"));
                assert!(x.contains("o"));
            }
        }
    };
}

fn main() {
    // One evaluation
    let counter = Cell::new(0_u8);
    let get_value_and_increment = || {
        counter.set(counter.get() + 1);
        "container"
    };

    once_by_reference!(get_value_and_increment());

    assert_eq!(1, counter.get());

    // Ownership not required
    let s = String::from("container");
    once_by_reference!(s);
    assert!(!s.is_empty());
}
```

Note that the `println` macro is a very old example, and so there might be simpler ways of writing something equivalent. For example, this also passes the quick test above:

```rust
macro_rules! once_by_reference {
    ($v:expr) => {
        let x = &$v;
        assert!(x.contains("a"));
        assert!(x.contains("e"));
        assert!(x.contains("i"));
        assert!(x.contains("o"));
    };
}
```

**Comment by joelparkerhenderson** [comment]
Oooh, that's nifty. First I've seen of match ref. You're right, that could solve things. I'll experiment with your approach today & tomorrow.

> Yes, but that goes against the point of semver — I should not need to change my source code when upgrading from one semantic version to another.

Are you familiar with the emacs spacebar heater? :-)

**Comment by pdh11** [comment]
Another example of code which works with earlier 9.x versions but fails to compile with 9.6.1:
```
struct Foo {
    s: String,
}

fn fnord() {
    let s = Mutex::new(Foo { s: "fnord".to_string() } );
    let inner = s.lock().unwrap();
    assert_contains!(inner.s, "nor");
}
```
The error is "error[E0507]: cannot move out of dereference of `MutexGuard<'_, Foo>`". Here it's not a question of picking the unexpected one out of pass-by-reference and pass-by-value: here, pass-by-value is not available at all.

**Comment by joelparkerhenderson** [comment]
Thank you. I'm working on this now through the weekend, and intend to update here within 24h.

**Comment by joelparkerhenderson** [comment]
Thank you. Right now I'm publishing version 9.6.2 which fixes these pass-by issues. 

And @pdh11 there's a new file `./tests/regressions/mutex.rs` with a struct mutex test, to ensure it compiles and succeeds.

Can you do me a favor and give it try, and let me know here if this solves your issues? 

Thank you, and thank you for your patience too.

**Comment by pdh11** [comment]
Can confirm, 9.7.0 works fine with the existing client code, I can remove the "<9.6" from my Cargo.toml now, thanks for sorting this out!

**Comment by pdh11** [comment]
Ah. Sorry to come back again, but my CI has found a new one:
```
#[derive(Default)]
struct Foo {
    seen: HashSet<String>
}

fn fnord(needle: &str) {
    let mut f = Foo::default();
    f.seen.insert("Fnord".to_string());
    assert_contains!(f.seen, needle);
}
```
This compiles and works with 9.4.0. but not 9.5.7 or 9.7.0 :(

If I change the assert_contains to use `*needle`, it works in 9.5.7 and 9.7.0 but not 9.4.0 :( :(

**Comment by joelparkerhenderson** [comment]
Thank you for the follow up. I intend to take a look within 24 hours, and update here.

**Comment by shepmaster** [comment]
Note that I don't think there's anything wrong with cutting losses and releasing a semver-incompatible version. If 9.6 had been called 10.0, I wouldn't have blinked at having to make changes to my code. I only opened the issue because the version number indicated that there were no API changes required.

**Comment by joelparkerhenderson** [comment]
FYI I'm publishing updates 9.5.8, 9.6.3., 9.7.1, with the fixes to the macro `assert_contains` to align it with the Rust standard libraries as above. 

I appreciate all your help and patience! <3

I've updated the code, the tests, and the docs with examples  of `assert_contains` working with

* A String without a borrow i.e. the second arg doesn't have an ampersand

* A Vec with a borrow i.e. the second arg needs an ampersand

* A Range, much like a Vec.

* A HashSet with two examples: 

  * One example uses a &str. This doesn't need an ampersand (because the &str type already has one) which triggers the Rust automatic compiler Borrow optimization. This is the example that @pdh11 is reporting.

  * One example uses a String. This does need an ampersand (because String type doesn't already have one) which makes the method do a comparison without any Borrow optimization.

**Comment by joelparkerhenderson** [comment]
Thanks all. If you have more feedback or ideas etc. then I'm all ears. I'm cleaning up old open issues, so I'll close this one now.
